import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layouts/navbar";
import Footer from "@/components/layouts/footer";
import { epicene, epiceneText, sohne } from "@/lib/fonts";
import CookiePopUpBox from "@/lib/cookiePopup";
import GAHandler from "@/lib/gaHandler";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const noIndex = process.env.NO_INDEX === "true";
  return (
    <html lang="en">
      <head>{noIndex && <meta name="robots" content="noindex" />}</head>
      <body
        className={`${epicene.variable} ${epiceneText.variable} ${sohne.variable} font-sans bg-grey-100 px-4 md:px-5`}
      >
        <Navbar />
        {children}
        <Footer />
        <Suspense>

        <GAHandler />
        </Suspense>
        <CookiePopUpBox />
      </body>
    </html>
  );
}
